doctrine:
    dbal:
        default_connection: shard
        connections:
            shard:
                url: '%env(resolve:DATABASE_URL)%'
            global:
                url: '%env(resolve:DATABASE_GLOBAL_URL)%'
