doctrine:
    dbal:
        default_connection: shard
        connections:
            shard:
                url: '%env(resolve:DATABASE_URL)%'
            global:
                url: '%env(resolve:DATABASE_GLOBAL_URL)%'

    orm:
        auto_generate_proxy_classes: true
        default_entity_manager: shard
        entity_managers:
            shard:
                connection: shard
                naming_strategy: doctrine.orm.naming_strategy.underscore
                mappings:
                    Shard:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Shard'
                        prefix: 'App\Entity\Shard'
                        alias: Shard
            global:
                connection: global
                naming_strategy: doctrine.orm.naming_strategy.underscore
                mappings:
                    Global:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Global'
                        prefix: 'App\Entity\Global'
                        alias: Global


when@test:
    doctrine:
        dbal:
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
