doctrine:
    dbal:
        default_connection: proton_mail_shard
        connections:
            proton_mail_shard:
                url: '%env(resolve:DATABASE_URL)%'
            proton_mail_global:
                url: '%env(resolve:DATABASE_GLOBAL_URL)%'
