version: '3.8'

services:
  # PHP-FPM service
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_php
    volumes:
      - .:/var/www/symfony
    ports:
      - "9000:9000"
    networks:
      - app-network

  mysql_shard:
    image: mysql:5.7
    container_name: mysql_shard
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfonypass
      MYSQL_DATABASE: proton_mail_shard
    ports:
      - "3307:3306"  # Note different port mapping
    networks:
      - app-network

  mysql_global:
    image: mysql:5.7
    container_name: mysql_global
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfonypass
      MYSQL_DATABASE: proton_mail_global
    ports:
      - "3308:3306"  # Note different port mapping
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

