parameters:

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        
    # Define BlobReferenceService as a regular service with its required dependencies
    App\Service\BlobReferenceService:
        arguments:
            $shardConnection: '@doctrine.dbal.shard'
            $globalConnection: '@doctrine.dbal.global'

    # Register the command and tag it as a console command
    App\Command\ProcessBlobReferencesCommand:
        arguments:
            $blobReferenceService: '@App\Service\BlobReferenceService'
        tags:
            - { name: 'console.command' }

    # Automatically register services in the src/ directory
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
