parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    # Command
    App\Command\CheckBlobConsistencyCommand:
        arguments:
            $getReferencesCounts: '@App\Service\GetReferencesCounts'
        tags:
            - { name: 'console.command' }
        public: true

    # Service
    App\Service\GetReferencesCounts:
        public: true

    App\Repository\Global\BlobStorageRepository:
        arguments:
            $connection: '@doctrine.dbal.proton_mail_global_connection'
        autowire: true
        autoconfigure: true

    App\Repository\Global\SentAttachmentRepository:
        arguments:
            $connection: '@doctrine.dbal.proton_mail_global_connection'
        autowire: true
        autoconfigure: true

    App\Repository\Global\SentMessageRepository:
        arguments:
            $connection: '@doctrine.dbal.proton_mail_global_connection'
        autowire: true
        autoconfigure: true

    App\Repository\Shard\AttachmentRepository:
        arguments:
            $connection: '@doctrine.dbal.proton_mail_shard_connection'
        autowire: true
        autoconfigure: true

    App\Repository\Shard\ContactDataRepository:
        arguments:
            $connection: '@doctrine.dbal.proton_mail_shard_connection'
        autowire: true
        autoconfigure: true

    App\Repository\Shard\MessageDataRepository:
        arguments:
            $connection: '@doctrine.dbal.proton_mail_shard_connection'
        autowire: true
        autoconfigure: true

    App\Repository\Shard\OutsideAttachmentRepository:
        arguments:
            $connection: '@doctrine.dbal.proton_mail_shard_connection'
        autowire: true
        autoconfigure: true

    App\Repository\Shard\BaseShardRepository:
        arguments:
            $connection: '@doctrine.dbal.proton_mail_shard_connection'
        autowire: true
        autoconfigure: true

    App\Repository\Global\BaseGlobalRepository:
        arguments:
            $connection: '@doctrine.dbal.proton_mail_global_connection'
        autowire: true
        autoconfigure: true


    # Generic service loader
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
